---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/os: linux
  name: sev-vm1
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: pvc-sev-vm1
    spec:
      source:
        http:
          url: <replace_with_vm_image_url>
      storage:
        resources:
          requests:
            storage: 30Gi
        storageClassName: hostpath-csi-local
  architecture: amd64
  running: true
  template:
    metadata:
      annotations:
        hooks.kubevirt.io/hookSidecars: '[{"args": ["--version", "v1alpha2"],
          "configMap": {"name": "sidecar-sev", "key": "my_script.sh", "hookPath": "/usr/bin/onDefineDomain"}}]'
    spec:
      domain:
        cpu:
          cores: 1
          maxSockets: 4
          model: host-model
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi:
            enabled: true
          smm:
            enabled: false
        firmware:
          bootloader:
            efi:
              secureBoot: false
        launchSecurity:
          sev: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: None
      hostname: sev-example
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: pvc-sev-vm1
        name: rootdisk
