apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-set-selinux-for-hostpath-provisioner
  labels:
    # Set the role to master if you installed SNO cluster;
    # set it to worker otherwise.
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Set SELinux chcon for hostpath provisioner
            Before=kubelet.service
            [Service]
            ExecStartPre=-mkdir -p /var/hpvolumes
            ExecStartPre=-chmod 666 /var/hpvolumes
            ExecStart=/usr/bin/chcon -Rt container_file_t /var/hpvolumes
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: hostpath-provisioner.service
