apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
    - name: hpp-csi-local
      # The storage path in the yaml file should be the one
      # created by hostpath machine config.
      path: "/var/hpvolumes"
  workload:
    nodeSelector:
      kubernetes.io/os: linux
